### PR TITLE
Adding compatibility with Chef 11

### PR DESCRIPTION
**Pull request by kdaniels**
This addresses the issue noted [here](https://github.com/bmarini/knife-inspect/issues/45) - I've tested and verified the fix on Chef 11.18.12.

### CODE REVIEW

**Comment by gregkare** [comment]
Hi, thanks!

I've merged master to your PR and added a few commits, can you get the kfd-chef11-fixes branch in this repo and use it in your chef repos? Thanks in advance

**Comment by kdaniels** [comment]
@gregkare done! And it's been working without issue in our chef repos.

**Comment by gregkare** [comment]
@kdaniels Great, thanks! I'll merge and release a new version soon (hopefully tomorrow)

**Comment by kdaniels** [comment]
@gregkare awesome, thanks a bunch!

**Comment by gregkare** [comment]
@kdaniels I have published 0.15.0 on RubyGems: https://rubygems.org/gems/knife-inspect/versions/0.15.0

**Pull request merged**
